name: 'Upload to Release Action'
description: 'A GitHub Action that uploads a file to a new release.'
author: 'Shopify'
inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Path to the file to upload'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
