name: "Release"
on: [release]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        name: LICENSE
        path: LICENSE
        content-type: text/plain
        repo-token: ${{ secrets.GITHUB_TOKEN }}
